# Generated by Django 4.1.4 on 2022-12-20 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apipagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentuser',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2022, 12, 21)),
        ),
        migrations.CreateModel(
            name='ExproredPauments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_fee_amount', models.FloatField(default=5.0)),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagouser', to='apipagos.paymentuser')),
            ],
        ),
    ]
